### ISSUE TITLE
Add CvC Prioritization Tracker Feature

### ISSUE THREAD

**Issue by RyanFWebb** [clingen-data-model/clinvar-curation-reporting#10]
> Implement a similar tracking feature to what's available in the VCEP tracker sheets.

This was requested on 10/19 by Julie and Eric. We will need specifications on what fields they would like to see in the tracker feature. We need to mock up the scenarios for handling refreshes that change values in the sheets.

**Comment by RyanFWebb** [comment]
My understanding to date is the need for a column on the outliers sheets to indicate what the "tracker status" is, with the ability to add variants to the tracker sheet and also record who annotated each record.

Define the minimal viable product with @jratliff1234 and Eric.

**Comment by RyanFWebb** [comment]
This is ready for review by Julie, Pam, etc.

**Comment by dazzariti** [comment]
Thanks Ryan, assigning to myself to review with Pam and Julie

**Comment by dazzariti** [comment]
Had @julieratliff take a look at this, after reviewing questions with Ryan, she said this is good to go, I'll close the ticket
