### ISSUE TITLE
Add CvC Annotation Outdated Column in ClinSig Tracker Sheet

### ISSUE THREAD

**Issue by RyanFWebb** [clingen-data-model/clinvar-curation-reporting#11]
> Add an outdated column for ClinSig sheet (If the curation is done it's outdated when the VCV has been updated since curation), prioritize these records highest in the ClinSig sheet.

Within the tracker feature of the ClinSig sheet, include a column that identifies if these curations are outdated.

**Comment by RyanFWebb** [comment]
Planning to discuss at next CVC meeting for clarification after checking in with @larrybabb.

**Comment by larrybabb** [comment]
@RyanFWebb what is the status of this? I thought we reviewed this and you and Julie were good. Let's update at today's stand up.

**Comment by RyanFWebb** [comment]
@larrybabb The Outdated Column was never added since Julie said the sheet was meeting her needs. I think this was just an idea that had been discussed but didn't need to be implemented later on.
