### ISSUE TITLE
Migrate "Non-contributory" to "Flagging candidate" in all ClinVar curation reports/functions

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-curation-reporting#12]
All data for past curations need to be changed from "non-contributory" to "flagging candidate" 
All google sheet reports and bq functions that have app scripts, conditional formatting, filters, column functions, etc that reference "non-contributory" need to be updated to work with this new term. These sheets include but are not necessarily limited to:

[CvCuration Annotations](https://docs.google.com/spreadsheets/d/1pzuWR409vSmoFX9inmoU6el6vjG0SniB1KrxWLeVpaA/edit#gid=1495804276)
[CvCuration Review & Submit](https://docs.google.com/spreadsheets/d/1rHwJqZPmQQqDlUzEnNfctj_44SvswyDMing5GTWD4Us/edit#gid=0)
[CvCuration Statistics](https://docs.google.com/spreadsheets/d/1oZbqvlMfcSjha32u2x-9V1KQE4IGnZ7d4wp9rA4vyXA/edit#gid=0)
[ClinVar ClinSig Outliers](https://docs.google.com/spreadsheets/d/11XbauM053vdOWhQzCFiOG0mcZ2MLG97g3ElEGueQaiQ/edit#gid=1097099018)

BQ functions:
[curated_variation_as_of()](https://console.cloud.google.com/bigquery?project=clingen-stage&ws=!1m4!1m3!8m2!1s583560269534!2sc62372fcffda4b168bf502eb01762658)
[cvc_curations_as_of()](https://console.cloud.google.com/bigquery?project=clingen-stage&ws=!1m4!1m3!8m2!1s583560269534!2s14d08ad55365486ebdc20bcdaae51beb)
[cvc_curations_impact_as_of()](https://console.cloud.google.com/bigquery?project=clingen-stage&ws=!1m4!1m3!8m2!1s583560269534!2s0b117a58f444415f9b2d9cda5699c618)
[cvc_submitter_curations_as_of()](https://console.cloud.google.com/bigquery?project=clingen-stage&ws=!1m4!1m3!8m2!1s583560269534!2sda9e42abfd0e4b808d209ae10676cf32)

**Comment by larrybabb** [comment]
@dazzariti please verify that the 4 downstream reports are still working as expected.

**Comment by dazzariti** [comment]
@larrybabb  I see "Flagging Candidate" replace "Non Contributory" in all the reports except [ClinVar ClinSig Outliers](https://docs.google.com/spreadsheets/d/11XbauM053vdOWhQzCFiOG0mcZ2MLG97g3ElEGueQaiQ/edit#gid=1097099018) - on the Outliers tab "non-contributory" is still a value in column N - just confirming that's intended.
