### ISSUE TITLE
Modify Review & Submit v2 sheet headers

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-curation-reporting#17]
Based on our meeting on 1/8/2024 with the CvC group 
Heidi suggested the following change to the Review & Submit sheet columns on the Curation QC sheet headers
- X, Y and Z
	- prior curation same version
	- prior curation submitted
	- prior curations

**Comment by larrybabb** [comment]
changes made. They should also appear with the same names and order on the other 2 sheets (Review & Submit, Curation Verify).

**Comment by dazzariti** [comment]
Confirmed these changes have been made
