### ISSUE TITLE
CvC annotations log 

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-reporting#19]
@larrybabb  to create a new stand alone sheet called 'CvC annotations log' (discussion from ClinVar Stakeholders meeting 12th Jan 2024). The purpose of this sheet will be to allow all curators to see a list of all the curated records that can be refreshed at any time.

Another consideration is to combine this sheet with the ClinSig Outliers to reduce the number of sheets. @RyanFWebb to consider if this makes sense.

@dazzariti

**Comment by larrybabb** [comment]
Ready for review. 
https://docs.google.com/spreadsheets/d/1FsFrtZPgU8glmOXZAijwNvpc2lCGmKJ8mr74Nxh1PBo/edit#gid=997621849
I set this sheet up to be super simple. Hit the "Refresh" button in the first cell (A1) to see the latest up-to-date records that have been curated. They are sorted in chronological order as submitted with the most recent showing up first. The "last refresh executed" date time will show up in row 1 of cols B,C&D.

**Comment by dazzariti** [comment]
This looks like it fits the request, closing the ticket
