### ISSUE TITLE
Stats for ACMG/future meetings

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-reporting#22]
Discussion from CvC Check in 02/26
Question from Melissa on what are the outcomes from this project so far - in relation to the number of conflicts in ClinVar that have been solved due to the CvC work.
Look at the total number of VCVs that have completely resolved conflicts and stratifying the resolution by either ClinGen or NCBI.
The next level is then to determine how many conflicts are partially resolved (for eg P, VUS, LB).
 In particular medically significant conflicts that have been resolved (for eg P vs VUS/LB), only leaving behind conflicts that are not significant (for eg VUS vs LB).

@dazzariti @larrybabb

**Comment by larrybabb** [comment]
Thank you @PamRobertson for entering this. I had created another issue for this same purpose. I will combine your description above with that issue for continued tracking.
