### ISSUE TITLE
Produce draft of CvCuration impact report/statistics

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-curation-reporting#23]
based on several recent conversations at the cvc and broad clingen meetings we have discussed the need and semi-urgency to creating a set of "impact statistics" from the cvcuration efforts.

Here are a sampling of the ideas discussed.

to do an impact we must define what are the 'before' and 'after' states being compared.
'before' for clingen this is the release date on which the cvcuration is created, for ncbi it is the release before the initial release date that they began flagging submissions
'after' for clingen is any release after the 'before' release up to and including the release that the targeted scv is flagged, updated or deleted, for ncbi it is the initial release date that they began flagging submissions

**How many flagged submissions (scvs) have caused a change to the overall vcv-level classification**
*(get the before and after counts by release date for each of the following use cases)*
* did the variant classification at the time of curation include clinsig classifications
* did a conflict resolved
* did all submissions end up flagged
* did clingen and/or ncbi cause to the change 
* did the curated scv get deleted by the submitter before being flagged
* did the curated scv get updated by the submitter before being flagged
* ???
* 

-- Discussion from CvC Check in 02/26 @PamRobertson
Question from Melissa on what are the outcomes from this project so far - in relation to the number of conflicts in ClinVar that have been solved due to the CvC work.
Look at the total number of VCVs that have completely resolved conflicts and stratifying the resolution by either ClinGen or NCBI.
The next level is then to determine how many conflicts are partially resolved (for eg P, VUS, LB).
In particular medically significant conflicts that have been resolved (for eg P vs VUS/LB), only leaving behind conflicts that are not significant (for eg VUS vs LB).

**Comment by larrybabb** [comment]
@dazzariti I started writing up some ideas on stats in the description above. I will start figuring out these "impact stats" using this, but it would be helpful if you would review and help guide me to make sure I'm delivering approximately what @heidi needs.  This will be a draft and I will try to prioritize it.

**Comment by dazzariti** [comment]
Let's review on April 12th call to make sure Heidi has the stats she needs for her May presentation

**Comment by dazzariti** [comment]
Reviewed on April 12th CvC check in

Heidi's immediate request:

- In an ideal world, at the moment the curation happens, did our curation resolve a conflict at the VCV level? 
- We want to capture every conflict we've resolved, even if it was later overwritten by a new submission

**Comment by dazzariti** [comment]
@larrybabb Just want to ping you on this, Heidi needs to submit her slides that will use these stats on Wednesday May 1
