### ISSUE TITLE
Claim with insufficient supporting evidence - do not autoreview

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-reporting#27]
Following discussion on the May 20th CvC call, it was suggested that for the chrome extension option 'claim with insufficient supporting evidence' that this should not be autoreviewed in the CvCuration Review & Submit v2 sheet (excluding Heidi). This is because this option does not meet the 2/3 criteria of flagging reasons, and should only be used when an SCV is very wrong, but requires experience to select this option.

@larrybabb @dazzariti @RyanFWebb

**Comment by dazzariti** [comment]
Discussed on July 12th call this request no longer needed, focus on curation training
