### ISSUE TITLE
Adding a gene name column to the CvC Annotation Log spreadsheet 

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-reporting#28]
Adding to the CvC Annotation Log spreadsheet a column for gene name which will display the gene associated with the SCV and for CNVs have the term 'multiple'. Ideally aim to have this done by 06/14/2024

@larrybabb @dazzariti @RyanFWebb

**Comment by larrybabb** [comment]
@PamRobertson I added the gene symbol to column C of the Annotation Log spreadsheet. Please review and let me know if this is satisfactory.

**Comment by PamRobertson** [comment]
Yes this is great - thank you so much @larrybabb, we can close this ticket.
