### ISSUE TITLE
Pre-Annotation Prioirity Report (aka ClinSig Outliers) v2 Enhancements

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-curation-reporting#3]
Updating this as of 2/12/2024 (lbabb/rwebb) - 
setting the focus of this epic to only the ClinSig Outlier changes still open from the original 9/5/2023 check-in. We will consider this epic complete once the remaining issue **"add annotation outdated column in clinsig outlier"** is closed and we will call that v2 of the ClinSig Outlier.  Any subsequent requests for changes on that report (or any other "pre-prioirization" type report should be considered a new epic/issue)
*************
(original description below)
Based on discussion at Sept 5th CvC check in.

Currently our CvC reports are mixed, curators are using several spreadsheets to prioritize their work and review their curations. These include:
[ClinVar ClinSig Outliers ](https://docs.google.com/spreadsheets/d/11XbauM053vdOWhQzCFiOG0mcZ2MLG97g3ElEGueQaiQ/edit#gid=510338763)
https://docs.google.com/spreadsheets/d/1oZbqvlMfcSjha32u2x-9V1KQE4IGnZ7d4wp9rA4vyXA/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1CXrhQYTKfXtFSI2K9808EZtniXe7ijxAgQceWfJfiW4/edit#gid=1686582240

We want to organize this data into two workbooks, one for the purpose of prioritizing data to curate (based on outlier status, or discrepancies) and the second for containing the existing curations to QC/review

Prioritization sheet includes:
- Outliers
- Intralaboratory conflicts
- Top 1K Variants with Most SCVs
_- Note: should contain information about which records in these sheets have been annotated by the Chrome extension_

QC Sheet:

- To review records that have been annotated by the Chrome extension

**Comment by dazzariti** [comment]
@RyanFWebb @larrybabb Just wanted to jot down these notes from our discussion on Tuesday with Julie and Heidi - we can take this ticket to our next meeting to get more specifics

**Comment by dazzariti** [comment]
Getting updated data to Julie and Eric is a pretty high priority, as they are currently working off of older data that is harder prioritize.

The top priority of this ticket would be adding a way to sort the ClinSig that haven’t been curated yet (Ryan will look into ways to indicate which discrepancies should be prioritized/sorted in the sheet - to help assign work to Eric

**Comment by larrybabb** [comment]
@RyanFWebb let me know if you are doing anything material on this ticket or not. let's sync up on a plan to get Julie/Eric what they need asap.

**Comment by RyanFWebb** [comment]
@larrybabb @dazzariti I can start work on this immediately. I was out Monday-Tuesday and was catching up on some items yesterday.

**Comment by dazzariti** [comment]
Ryan will work with Julie on specifications (based on October 17 Broad ClinGen Weekly meeting discussion)

**Comment by RyanFWebb** [comment]
Met with Julie and Eric on 10/19 and they provided the following feedback:

- Implement a similar tracking feature to what's available in the VCEP tracker sheets.
- Add an outdated column for ClinSig sheet (If the curation is done it's outdated when the VCV has been updated since curation), prioritize these records highest in the ClinSig sheet.
- Combine ClinSig/QC in one place for efficiency.
- Julie is wondering if the QC sheet is unnecessary if an outdated field is added to ClinSig sheet, @larrybabb mentioned we should structure the QC sheet so that it is the primary sheet being used.

**Comment by larrybabb** [comment]
@dazzariti Ryan and I are doing some planning. We reviewed this epic and feel as if it should be more narrowly focused until we have concrete requirements for either updating/integrating the Top1K report. As far as the Statistics v3 report, that has now been integrated into the Annotation Log report so it is no longer relevant. Thus we want to make this epic only about the "Outlier" report.  Let us know if you have any concerns about that.

**Comment by dazzariti** [comment]
Sounds good to me!

**Comment by dazzariti** [comment]
Based on March 8 CvC call - this request is complete.
