### ISSUE TITLE
Improving prioritization of ClinSig Outliers sheet

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-curation-reporting#4]
Part of the discussion was on focused on how to make the Outlier report more user friendly and easier to prioritize [ClinVar ClinSig Outliers ](https://docs.google.com/spreadsheets/d/11XbauM053vdOWhQzCFiOG0mcZ2MLG97g3ElEGueQaiQ/edit#gid=510338763) - need a way to sort the outliers that haven’t been curated yet, Ryan will look into ways to indicate which discrepancies should be prioritized/sorted in the sheet (either biggest outlier percent, most discrepant, oldest date last evaluated etc.),

**Comment by RyanFWebb** [comment]
The [ClinVar ClinSig Outliers](https://docs.google.com/spreadsheets/d/11XbauM053vdOWhQzCFiOG0mcZ2MLG97g3ElEGueQaiQ/edit#gid=510338763) sheet has two new sheets, A-L Tracker and M-Z Tracker. These prioritize clinically significant outliers first by clinical significance, followed by outlier percentage (<33.3% per the READ.ME sheet), followed by curation status (no curations, partially resolved, no change only, and fully resolved in that order as recommended by Julie), then by gene.

Records link directly to ClinVar for annotation.

**Comment by hdziadzio** [comment]
@dazzariti please ask Pam to review

**Comment by dazzariti** [comment]
Confirmed with Pam this can be closed.
