### ISSUE TITLE
"No curations" not changing after refresh

### ISSUE THREAD

**Issue by RyanFWebb** [clingen-data-model/clinvar-curation-reporting#9]
> The curation status, "no curations", is still appearing even after being curated and the sheet is refreshed.

This was reported by Julie on 10/19, we need explicit examples of what's not working. It seems to work in the ClinSig Outliers sheet.

**Comment by RyanFWebb** [comment]
Waiting on Julie to provide explicit examples of issue.

**Comment by jratliff1234** [comment]
Currently, after I try to refresh, it still shows variants that have been annotated as no curations. The refresh button has a bug somehow.

**Comment by jratliff1234** [comment]
I think the issue is that I do not have permission to refresh.

**Comment by jratliff1234** [comment]
Actually I think it’s working now. Thanks!
